export default[
    {
        imageUrl:'/coverImages/image1.jpg'
    },
    {
        imageUrl:'/coverImages/image2.jpg'
    },
    {
        imageUrl:'/coverImages/image3.jpg'
    },
    {
        imageUrl:'/coverImages/image4.jpg'
    },
    {
        imageUrl:'/coverImages/image5.jpg'
    },
    {
        imageUrl:'/coverImages/image6.jpg'
    },
    {
        imageUrl:'/coverImages/image7.jpg'
    },
    {
        imageUrl:'/coverImages/image8.jpg'
    },
    {
        imageUrl:'/coverImages/image9.jpg'
    },
    {
        imageUrl:'/coverImages/image10.jpg'
    },
]